// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.hss01248.flipper_util;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class FlipperPigeon {

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class FlipperDioApiCodec extends StandardMessageCodec {
    public static final FlipperDioApiCodec INSTANCE = new FlipperDioApiCodec();
    private FlipperDioApiCodec() {}
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface FlipperDioApi {
    void reportRequest(String requestId, Long timeStamp, String uri, String method, Map<String, String> headers, String body, Result<Void> result);
    void reportResponse(String requestId, Long timeStamp, Long statusCode, String statusReason, Map<String, String> headers, String body, Result<Void> result);

    /** The codec used by FlipperDioApi. */
    static MessageCodec<Object> getCodec() {
      return FlipperDioApiCodec.INSTANCE;
    }

    /** Sets up an instance of `FlipperDioApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, FlipperDioApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.FlipperDioApi.reportRequest", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String requestIdArg = (String)args.get(0);
              if (requestIdArg == null) {
                throw new NullPointerException("requestIdArg unexpectedly null.");
              }
              Number timeStampArg = (Number)args.get(1);
              if (timeStampArg == null) {
                throw new NullPointerException("timeStampArg unexpectedly null.");
              }
              String uriArg = (String)args.get(2);
              if (uriArg == null) {
                throw new NullPointerException("uriArg unexpectedly null.");
              }
              String methodArg = (String)args.get(3);
              if (methodArg == null) {
                throw new NullPointerException("methodArg unexpectedly null.");
              }
              Map<String, String> headersArg = (Map<String, String>)args.get(4);
              if (headersArg == null) {
                throw new NullPointerException("headersArg unexpectedly null.");
              }
              String bodyArg = (String)args.get(5);
              if (bodyArg == null) {
                throw new NullPointerException("bodyArg unexpectedly null.");
              }
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.put("result", null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.reportRequest(requestIdArg, timeStampArg.longValue(), uriArg, methodArg, headersArg, bodyArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.FlipperDioApi.reportResponse", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String requestIdArg = (String)args.get(0);
              if (requestIdArg == null) {
                throw new NullPointerException("requestIdArg unexpectedly null.");
              }
              Number timeStampArg = (Number)args.get(1);
              if (timeStampArg == null) {
                throw new NullPointerException("timeStampArg unexpectedly null.");
              }
              Number statusCodeArg = (Number)args.get(2);
              if (statusCodeArg == null) {
                throw new NullPointerException("statusCodeArg unexpectedly null.");
              }
              String statusReasonArg = (String)args.get(3);
              if (statusReasonArg == null) {
                throw new NullPointerException("statusReasonArg unexpectedly null.");
              }
              Map<String, String> headersArg = (Map<String, String>)args.get(4);
              if (headersArg == null) {
                throw new NullPointerException("headersArg unexpectedly null.");
              }
              String bodyArg = (String)args.get(5);
              if (bodyArg == null) {
                throw new NullPointerException("bodyArg unexpectedly null.");
              }
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.put("result", null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.reportResponse(requestIdArg, timeStampArg.longValue(), statusCodeArg.longValue(), statusReasonArg, headersArg, bodyArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
