// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTFlipperDioApi.
NSObject<FlutterMessageCodec> *FLTFlipperDioApiGetCodec(void);

@protocol FLTFlipperDioApi
/// @return `nil` only when `error != nil`.
- (void)reportRequestRequestId:(nullable NSString *)requestId timeStamp:(nullable NSNumber *)timeStamp uri:(nullable NSString *)uri method:(nullable NSString *)method headers:(nullable NSDictionary<NSString *, NSString *> *)headers body:(nullable NSString *)body completion:(void(^)(FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (void)reportResponseRequestId:(nullable NSString *)requestId timeStamp:(nullable NSNumber *)timeStamp statusCode:(nullable NSNumber *)statusCode statusReason:(nullable NSString *)statusReason headers:(nullable NSDictionary<NSString *, NSString *> *)headers body:(nullable NSString *)body completion:(void(^)(FlutterError *_Nullable))completion;
@end

extern void FLTFlipperDioApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTFlipperDioApi> *_Nullable api);

NS_ASSUME_NONNULL_END
